version: '3.8'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    restart: always
    networks:
      - mongo-cluster
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: "rs0"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    restart: always
    networks:
      - mongo-cluster
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: "rs0"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    restart: always
    networks:
      - mongo-cluster
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: "rs0"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo3-data:/data/db

networks:
  mongo-cluster:
    external: true

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
